[default]
DB_USER = "fexservice"
DB_NAME = "fexservice"
DATABASE_URL = "sqlite:///:memory:"
SEARCH_QUERY= "topic:\"flask-extension flask-extensions\"" 
DELAY = 10
PRIORITY = 100
LOGGER_FILE = "log.log"
LOGGER_LEVEL = "DEBUG"
GITHUB_TOKEN = "@format {env[GITHUB_TOKEN]}"
